name: test

on:
  push:
    branches:
      - main
jobs:
  test:
    name: testen
    runs-on: ubuntu-latest

    steps:
    -uses: actions/checkout@v3
    -name: Set up Python 3.11
    uses: actions/setup-python@v4
    with:
      python-version: 3.11
      
    -name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       if [ -f Übung2.py ]; then pip install -r Übung2.py; fi
       pip install pylint pytest-cov pylint-exit
       
    -name: Analysing the code with pylint
     run: |
       pylint Übung2/ --disable=C0111 || pylint-exit $?

    -name: Test the code with pytest
     run: |
       pytest 
