name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest-cov pylint-exit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint ep_exercise2 --disable=C0111 || pylint-exit $?
    - name: Test the code with pytest
      run: |
        pytest --cov=test_ep_exercise2 --cov-fail-under=90 --cov-branch 
